/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant;
import java.util.*;
import java.text.*;
import java.awt.*;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Tanzim
 */
public class RestaurantFrom extends javax.swing.JFrame {
    double [] i = new double[20];
    double [] j = new double[10];
    double [] s = new double[20];
    double [] t = new double[18];
    /**
     * Creates new form RestaurantFrom
     */
    public RestaurantFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcost1 = new javax.swing.JTextField();
        jcost2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jsubt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jdc = new javax.swing.JTextField();
        jtax = new javax.swing.JTextField();
        jdtotal = new javax.swing.JTextField();
        jtotal = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtd3 = new javax.swing.JTextField();
        jtxtd2 = new javax.swing.JTextField();
        jtxtd = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        jcalculator = new javax.swing.JButton();
        jrpt = new javax.swing.JButton();
        jcash = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jexit1 = new javax.swing.JButton();
        jrset = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Management System");
        setPreferredSize(new java.awt.Dimension(1318, 718));
        setResizable(false);
        setSize(new java.awt.Dimension(1318, 718));
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        jPanel4.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText("Receipt");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(150, 0, 60, 26);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 310, 364);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(274, 415, 63, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(940, 40, 348, 460);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 2, true));

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0), 2));
        jPanel3.setLayout(null);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 51, 204));
        jCheckBox1.setText("Parata- 2 Pcs");
        jCheckBox1.setBorder(null);
        jCheckBox1.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1);
        jCheckBox1.setBounds(10, 10, 230, 31);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(0, 51, 204));
        jCheckBox2.setText("Chapatti- 2 pcs");
        jCheckBox2.setBorder(null);
        jCheckBox2.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseClicked(evt);
            }
        });
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox2);
        jCheckBox2.setBounds(10, 50, 230, 31);

        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextField1.setText("TK. 30/- (BDT) ");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        jTextField1.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField1MouseEntered(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1);
        jTextField1.setBounds(310, 10, 154, 31);
        jTextField1.getAccessibleContext().setAccessibleDescription("");

        jTextField2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextField2.setText("TK. 40/- (BDT) ");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        jTextField2.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(310, 50, 154, 31);
        jTextField2.getAccessibleContext().setAccessibleDescription("");

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(0, 51, 204));
        jCheckBox3.setText("Mixed Vegetable");
        jCheckBox3.setBorder(null);
        jCheckBox3.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox3MouseClicked(evt);
            }
        });
        jPanel3.add(jCheckBox3);
        jCheckBox3.setBounds(10, 90, 230, 31);

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(0, 51, 204));
        jCheckBox4.setText("Sujir Halwa");
        jCheckBox4.setBorder(null);
        jCheckBox4.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox4MouseClicked(evt);
            }
        });
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox4);
        jCheckBox4.setBounds(10, 130, 230, 31);

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(0, 51, 204));
        jCheckBox5.setText("Bhaji ");
        jCheckBox5.setBorder(null);
        jCheckBox5.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox5MouseClicked(evt);
            }
        });
        jPanel3.add(jCheckBox5);
        jCheckBox5.setBounds(10, 170, 230, 31);

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(0, 51, 204));
        jCheckBox6.setText("Toast- 2 Slices");
        jCheckBox6.setBorder(null);
        jCheckBox6.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox6MouseClicked(evt);
            }
        });
        jPanel3.add(jCheckBox6);
        jCheckBox6.setBounds(10, 210, 230, 31);

        jCheckBox7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(0, 51, 204));
        jCheckBox7.setText("French Toast");
        jCheckBox7.setBorder(null);
        jCheckBox7.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox7MouseClicked(evt);
            }
        });
        jPanel3.add(jCheckBox7);
        jCheckBox7.setBounds(10, 250, 230, 31);

        jCheckBox8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(0, 51, 204));
        jCheckBox8.setText("Two Fresh Eggs any style");
        jCheckBox8.setBorder(null);
        jCheckBox8.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox8MouseClicked(evt);
            }
        });
        jPanel3.add(jCheckBox8);
        jCheckBox8.setBounds(10, 290, 230, 31);

        jCheckBox9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(0, 51, 204));
        jCheckBox9.setText("Bread Basket- 6 Rolls of Bread");
        jCheckBox9.setBorder(null);
        jCheckBox9.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox9MouseClicked(evt);
            }
        });
        jPanel3.add(jCheckBox9);
        jCheckBox9.setBounds(10, 330, 230, 31);

        jCheckBox10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox10.setForeground(new java.awt.Color(0, 51, 204));
        jCheckBox10.setText("Sausage ");
        jCheckBox10.setBorder(null);
        jCheckBox10.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox10MouseClicked(evt);
            }
        });
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox10);
        jCheckBox10.setBounds(10, 370, 230, 31);

        jTextField3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextField3.setText("TK. 30/- (BDT) ");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        jTextField3.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jPanel3.add(jTextField3);
        jTextField3.setBounds(310, 90, 154, 31);
        jTextField3.getAccessibleContext().setAccessibleDescription("");

        jTextField4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextField4.setText("TK. 30/- (BDT)");
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        jTextField4.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jPanel3.add(jTextField4);
        jTextField4.setBounds(310, 130, 154, 31);
        jTextField4.getAccessibleContext().setAccessibleDescription("");

        jTextField5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextField5.setText("TK. 40/- (BDT) ");
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        jTextField5.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jPanel3.add(jTextField5);
        jTextField5.setBounds(310, 370, 154, 31);
        jTextField5.getAccessibleContext().setAccessibleDescription("");

        jTextField6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextField6.setText("TK. 90/- (BDT) ");
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        jTextField6.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        jPanel3.add(jTextField6);
        jTextField6.setBounds(310, 330, 154, 31);
        jTextField6.getAccessibleContext().setAccessibleDescription("");

        jTextField7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextField7.setText("TK. 30/- (BDT) ");
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        jTextField7.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        jPanel3.add(jTextField7);
        jTextField7.setBounds(310, 290, 154, 31);
        jTextField7.getAccessibleContext().setAccessibleDescription("");

        jTextField8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextField8.setText("TK. 40/- (BDT) ");
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        jTextField8.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
        });
        jPanel3.add(jTextField8);
        jTextField8.setBounds(310, 250, 154, 31);
        jTextField8.getAccessibleContext().setAccessibleDescription("");

        jTextField9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextField9.setText("TK. 20/- (BDT)");
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        jTextField9.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
        });
        jPanel3.add(jTextField9);
        jTextField9.setBounds(310, 210, 154, 31);
        jTextField9.getAccessibleContext().setAccessibleDescription("");

        jTextField10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextField10.setText("TK. 20/- (BDT)");
        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        jTextField10.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField10MouseClicked(evt);
            }
        });
        jPanel3.add(jTextField10);
        jTextField10.setBounds(310, 170, 154, 31);
        jTextField10.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane2.addTab("Breakfast", jPanel3);

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        jPanel8.setForeground(new java.awt.Color(51, 51, 255));
        jPanel8.setLayout(null);

        jCheckBox11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox11.setForeground(new java.awt.Color(51, 51, 255));
        jCheckBox11.setText("Rice one Person");
        jCheckBox11.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox11MouseClicked(evt);
            }
        });
        jPanel8.add(jCheckBox11);
        jCheckBox11.setBounds(8, 9, 230, 31);

        jCheckBox12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox12.setForeground(new java.awt.Color(51, 51, 255));
        jCheckBox12.setText("Seasonal Salad");
        jCheckBox12.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox12MouseClicked(evt);
            }
        });
        jPanel8.add(jCheckBox12);
        jCheckBox12.setBounds(8, 48, 230, 31);

        jCheckBox13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox13.setForeground(new java.awt.Color(51, 51, 255));
        jCheckBox13.setText("Daal Chorchori");
        jCheckBox13.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox13MouseClicked(evt);
            }
        });
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        jPanel8.add(jCheckBox13);
        jCheckBox13.setBounds(8, 86, 230, 31);

        jCheckBox14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox14.setForeground(new java.awt.Color(51, 51, 255));
        jCheckBox14.setText("Vegetable Curry");
        jCheckBox14.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox14MouseClicked(evt);
            }
        });
        jPanel8.add(jCheckBox14);
        jCheckBox14.setBounds(8, 126, 230, 31);

        jCheckBox15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox15.setForeground(new java.awt.Color(51, 51, 255));
        jCheckBox15.setText("Prawn bhuna");
        jCheckBox15.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox15MouseClicked(evt);
            }
        });
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });
        jPanel8.add(jCheckBox15);
        jCheckBox15.setBounds(8, 169, 230, 31);

        jCheckBox16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox16.setForeground(new java.awt.Color(51, 51, 255));
        jCheckBox16.setText("Chingri Malaikari");
        jCheckBox16.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox16MouseClicked(evt);
            }
        });
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });
        jPanel8.add(jCheckBox16);
        jCheckBox16.setBounds(8, 209, 230, 31);

        jCheckBox17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox17.setForeground(new java.awt.Color(51, 51, 255));
        jCheckBox17.setText("Fish Curry");
        jCheckBox17.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox17MouseClicked(evt);
            }
        });
        jPanel8.add(jCheckBox17);
        jCheckBox17.setBounds(8, 246, 230, 31);

        jCheckBox18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox18.setForeground(new java.awt.Color(51, 51, 255));
        jCheckBox18.setText("Mutton Rtezala");
        jCheckBox18.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox18MouseClicked(evt);
            }
        });
        jPanel8.add(jCheckBox18);
        jCheckBox18.setBounds(8, 288, 230, 31);

        jCheckBox19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox19.setForeground(new java.awt.Color(51, 51, 255));
        jCheckBox19.setText("Chicken Razala");
        jCheckBox19.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox19MouseClicked(evt);
            }
        });
        jPanel8.add(jCheckBox19);
        jCheckBox19.setBounds(8, 333, 230, 31);

        jCheckBox20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox20.setForeground(new java.awt.Color(51, 51, 255));
        jCheckBox20.setText("Beef Curry");
        jCheckBox20.setPreferredSize(new java.awt.Dimension(230, 31));
        jCheckBox20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox20MouseClicked(evt);
            }
        });
        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });
        jPanel8.add(jCheckBox20);
        jCheckBox20.setBounds(8, 372, 230, 31);

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField11.setText("TK. 30/- (BDT) ");
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        jTextField11.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField11MouseClicked(evt);
            }
        });
        jPanel8.add(jTextField11);
        jTextField11.setBounds(302, 10, 154, 31);

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField12.setText("TK. 40/- (BDT) ");
        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        jTextField12.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField12MouseClicked(evt);
            }
        });
        jPanel8.add(jTextField12);
        jTextField12.setBounds(302, 48, 154, 31);

        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField13.setText("TK. 40/- (BDT) ");
        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        jTextField13.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField13MouseClicked(evt);
            }
        });
        jPanel8.add(jTextField13);
        jTextField13.setBounds(302, 86, 154, 31);

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField14.setText("TK. 50/- (BDT) ");
        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        jTextField14.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField14MouseClicked(evt);
            }
        });
        jPanel8.add(jTextField14);
        jTextField14.setBounds(302, 130, 154, 31);

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField15.setText("TK. 60/- (BDT) ");
        jTextField15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        jTextField15.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField15MouseClicked(evt);
            }
        });
        jPanel8.add(jTextField15);
        jTextField15.setBounds(302, 173, 154, 31);

        jTextField16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField16.setText("TK. 100/- (BDT) ");
        jTextField16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        jTextField16.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField16MouseClicked(evt);
            }
        });
        jPanel8.add(jTextField16);
        jTextField16.setBounds(302, 214, 154, 31);

        jTextField17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField17.setText("TK. 120/- (BDT) ");
        jTextField17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        jTextField17.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField17MouseClicked(evt);
            }
        });
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField17);
        jTextField17.setBounds(302, 252, 154, 31);

        jTextField18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField18.setText("TK. 200/- (BDT) ");
        jTextField18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        jTextField18.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField18MouseClicked(evt);
            }
        });
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField18);
        jTextField18.setBounds(302, 291, 154, 31);

        jTextField19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField19.setText("TK. 215/- (BDT) ");
        jTextField19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        jTextField19.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField19MouseClicked(evt);
            }
        });
        jPanel8.add(jTextField19);
        jTextField19.setBounds(302, 332, 154, 31);

        jTextField20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField20.setText("TK. 300/- (BDT) ");
        jTextField20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        jTextField20.setPreferredSize(new java.awt.Dimension(154, 31));
        jTextField20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField20MouseClicked(evt);
            }
        });
        jPanel8.add(jTextField20);
        jTextField20.setBounds(302, 373, 154, 31);

        jTabbedPane2.addTab("Meal", jPanel8);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 44, 520, 460);

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 2, 3, new java.awt.Color(0, 102, 102)));
        jPanel5.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("Cost Of Foods");
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 31));
        jPanel5.add(jLabel1);
        jLabel1.setBounds(30, 10, 130, 31);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Cost Of Drinks");
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 31));
        jPanel5.add(jLabel2);
        jLabel2.setBounds(30, 60, 130, 31);

        jcost1.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jcost1.setForeground(new java.awt.Color(255, 0, 255));
        jcost1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jcost1.setText("0.00");
        jcost1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        jcost1.setPreferredSize(new java.awt.Dimension(130, 31));
        jPanel5.add(jcost1);
        jcost1.setBounds(280, 10, 130, 31);

        jcost2.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jcost2.setForeground(new java.awt.Color(0, 51, 255));
        jcost2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jcost2.setText("0.00");
        jcost2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        jcost2.setPreferredSize(new java.awt.Dimension(130, 31));
        jcost2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcost2ActionPerformed(evt);
            }
        });
        jPanel5.add(jcost2);
        jcost2.setBounds(280, 60, 130, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 255));
        jLabel3.setText("Sub Total");
        jLabel3.setPreferredSize(new java.awt.Dimension(130, 31));
        jPanel5.add(jLabel3);
        jLabel3.setBounds(30, 110, 130, 31);

        jsubt.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jsubt.setForeground(new java.awt.Color(255, 0, 102));
        jsubt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jsubt.setText("0.00");
        jsubt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        jsubt.setPreferredSize(new java.awt.Dimension(130, 31));
        jsubt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsubtMouseClicked(evt);
            }
        });
        jPanel5.add(jsubt);
        jsubt.setBounds(280, 110, 130, 31);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(10, 510, 440, 160);

        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 2, 3, new java.awt.Color(0, 102, 102)));
        jPanel7.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Tax");
        jLabel5.setPreferredSize(new java.awt.Dimension(130, 31));
        jPanel7.add(jLabel5);
        jLabel5.setBounds(29, 66, 130, 31);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Total");
        jLabel6.setPreferredSize(new java.awt.Dimension(38, 31));
        jPanel7.add(jLabel6);
        jLabel6.setBounds(30, 116, 60, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Cost Of Delivery");
        jLabel4.setPreferredSize(new java.awt.Dimension(130, 31));
        jPanel7.add(jLabel4);
        jLabel4.setBounds(29, 13, 130, 31);

        jdc.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jdc.setForeground(new java.awt.Color(0, 0, 204));
        jdc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jdc.setText("0.00");
        jdc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        jdc.setPreferredSize(new java.awt.Dimension(130, 31));
        jPanel7.add(jdc);
        jdc.setBounds(287, 13, 130, 31);

        jtax.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jtax.setForeground(new java.awt.Color(0, 0, 204));
        jtax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtax.setText("0.00");
        jtax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        jtax.setPreferredSize(new java.awt.Dimension(130, 31));
        jPanel7.add(jtax);
        jtax.setBounds(287, 66, 130, 31);

        jdtotal.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jdtotal.setForeground(new java.awt.Color(0, 0, 204));
        jdtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jdtotal.setText("0.00");
        jdtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        jdtotal.setPreferredSize(new java.awt.Dimension(130, 31));
        jPanel7.add(jdtotal);
        jdtotal.setBounds(287, 118, 130, 31);

        jtotal.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jtotal.setForeground(new java.awt.Color(51, 51, 255));
        jtotal.setText("Total");
        jtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtotalActionPerformed(evt);
            }
        });
        jPanel7.add(jtotal);
        jtotal.setBounds(140, 118, 95, 30);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(460, 510, 450, 160);

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 102));
        jLabel7.setText("Drinks");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText(" Tea & Coffee");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setText("Soft Drinks");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 255));
        jLabel10.setText("Cold Drinks");

        jtxtd3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtd3.setForeground(new java.awt.Color(51, 51, 255));

        jtxtd2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtd2.setForeground(new java.awt.Color(51, 51, 255));

        jtxtd.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxtd.setForeground(new java.awt.Color(102, 102, 255));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(102, 102, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a item", "Tea-15/-", "Green Tea-25/-", "Cappuccino-100/-", "Iced Coffee-65/-", "Coffee Milk-70/-" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(102, 102, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a item", "7UP-15/-", "Coke-15/-", "Mango Juice-40/-", "Apple Juice-35/-", "Orange Juice-35/-" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(102, 102, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Setect a item", "Coconut Milk-60/-", "Original Iced Chocolate-100/-", "Very Vanilla Chiller-80/-", "Cookies and Cream-90/-", "Fruize Mango-80/-" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(jtxtd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtd2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtd3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox3, 0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(48, 48, 48)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jtxtd2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtd3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jCheckBox21.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jCheckBox21.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBox21.setText("Delivery Cost");
        jCheckBox21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox21MouseClicked(evt);
            }
        });
        jCheckBox21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox21ActionPerformed(evt);
            }
        });

        jCheckBox22.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jCheckBox22.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBox22.setText("Tax");
        jCheckBox22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox22MouseClicked(evt);
            }
        });
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jCheckBox21)
                        .addGap(28, 28, 28)
                        .addComponent(jCheckBox22, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox21)
                    .addComponent(jCheckBox22))
                .addGap(5, 5, 5))
        );

        getContentPane().add(jPanel9);
        jPanel9.setBounds(580, 40, 310, 460);

        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 2, 3, new java.awt.Color(0, 102, 102)));
        jPanel13.setLayout(null);

        jcalculator.setBackground(new java.awt.Color(255, 102, 102));
        jcalculator.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jcalculator.setForeground(new java.awt.Color(0, 51, 204));
        jcalculator.setText("Calculator");
        jcalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcalculatorActionPerformed(evt);
            }
        });
        jPanel13.add(jcalculator);
        jcalculator.setBounds(30, 20, 136, 44);

        jrpt.setBackground(new java.awt.Color(255, 102, 102));
        jrpt.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jrpt.setForeground(new java.awt.Color(0, 51, 204));
        jrpt.setText("Receipt");
        jrpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrptActionPerformed(evt);
            }
        });
        jPanel13.add(jrpt);
        jrpt.setBounds(200, 20, 140, 44);

        jcash.setBackground(new java.awt.Color(255, 0, 51));
        jcash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcash.setForeground(new java.awt.Color(51, 102, 255));
        jcash.setText("Cash");
        jcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcashActionPerformed(evt);
            }
        });
        jPanel13.add(jcash);
        jcash.setBounds(103, 90, 160, 40);

        getContentPane().add(jPanel13);
        jPanel13.setBounds(940, 510, 350, 160);

        jLabel11.setFont(new java.awt.Font("Bodoni MT Black", 2, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 204));
        jLabel11.setText("Restaurant Managermet System");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(520, 0, 330, 38);

        jexit1.setBackground(new java.awt.Color(255, 0, 51));
        jexit1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jexit1.setForeground(new java.awt.Color(51, 0, 255));
        jexit1.setText("Exit");
        jexit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexit1ActionPerformed(evt);
            }
        });
        getContentPane().add(jexit1);
        jexit1.setBounds(1180, 9, 90, 30);

        jrset.setBackground(new java.awt.Color(0, 102, 255));
        jrset.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jrset.setForeground(new java.awt.Color(204, 0, 51));
        jrset.setText("Reset");
        jrset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrsetActionPerformed(evt);
            }
        });
        getContentPane().add(jrset);
        jrset.setBounds(1070, 10, 90, 29);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tanzim\\Pictures\\home.jpg")); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 1310, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        double x=Double.parseDouble(jcost1.getText());
        double y=Double.parseDouble(jsubt.getText());
        double a=Double.parseDouble(jTextField1.getText());
        double a2=30;
        if (jCheckBox1.isSelected()) 
        {
            i[0] =(a*a2)+x;
            s[0] =(a*a2)+y;
            String z = String.format("%.2f",i[0]);
            jcost1.setText(z);
            String sb = String.format("%.2f",s[0]);
            jsubt.setText(sb);
 
        }
        
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jCheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseClicked
        double x=Double.parseDouble(jcost1.getText());
        double y=Double.parseDouble(jsubt.getText());
        double b=Double.parseDouble(jTextField2.getText());
        double b2=40;
        if (jCheckBox2.isSelected())
        {
            i[1] =(b*b2)+x;
            String z = String.format("%.2f",i[1]);
            jcost1.setText(z);
            s[1] =(b*b2)+y;
            String sb = String.format("%.2f",s[1]);
            jsubt.setText(sb);
        }
    }//GEN-LAST:event_jCheckBox2MouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
       
         jTextField1.setText(null);   
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseEntered
        
    }//GEN-LAST:event_jTextField1MouseEntered

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
         jTextField2.setText(null); 
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
         jTextField3.setText(null); 
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        jTextField4.setText(null);
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MouseClicked
        jTextField10.setText(null);
    }//GEN-LAST:event_jTextField10MouseClicked

    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked
        jTextField9.setText(null);
    }//GEN-LAST:event_jTextField9MouseClicked

    private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked
       jTextField8.setText(null);
    }//GEN-LAST:event_jTextField8MouseClicked

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        jTextField7.setText(null);
    }//GEN-LAST:event_jTextField7MouseClicked

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        jTextField6.setText(null);
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        jTextField5.setText(null);
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jCheckBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MouseClicked
       double x=Double.parseDouble(jcost1.getText());
       double y=Double.parseDouble(jsubt.getText());
        double c1=Double.parseDouble(jTextField3.getText());
        double c2=30;
        if (jCheckBox3.isSelected()) 
        {
            i[2] =(c1*c2)+x;
            String z = String.format("%.2f",i[2]);
            jcost1.setText(z);
             s[2] =(c1*c2)+y;
            String sb = String.format("%.2f",s[2]);
            jsubt.setText(sb);
        }
    }//GEN-LAST:event_jCheckBox3MouseClicked

    private void jCheckBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox4MouseClicked
         double x=Double.parseDouble(jcost1.getText());
         double y=Double.parseDouble(jsubt.getText());
        double d1=Double.parseDouble(jTextField4.getText());
        double d2=30;
        if (jCheckBox4.isSelected())
        {
            i[3] =(d1*d2)+x;
            String z = String.format("%.2f",i[3]);
            jcost1.setText(z);
            s[3] =(d1*d2)+y;
            String sb = String.format("%.2f",s[3]);
            jsubt.setText(sb);
        }
    }//GEN-LAST:event_jCheckBox4MouseClicked

    private void jCheckBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox5MouseClicked
        double x=Double.parseDouble(jcost1.getText());
        double y=Double.parseDouble(jsubt.getText());
        double e1=Double.parseDouble(jTextField10.getText());
        double e2=20;
        if (jCheckBox5.isSelected())
        {
            i[4] =(e1*e2)+x;
            String z = String.format("%.2f",i[4]);
            jcost1.setText(z);
            s[4] =(e1*e2)+y;
            String sb = String.format("%.2f",s[4]);
            jsubt.setText(sb);
        }
    }//GEN-LAST:event_jCheckBox5MouseClicked

    private void jCheckBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox6MouseClicked
        double x=Double.parseDouble(jcost1.getText());
        double y=Double.parseDouble(jsubt.getText());
        double f1=Double.parseDouble(jTextField9.getText());
        double f2=30;
        if (jCheckBox6.isSelected())
        {
            i[5] =(f1*f2)+x;
            String z = String.format("%.2f",i[5]);
            jcost1.setText(z);
            s[5] =(f1*f2)+y;
            String sb = String.format("%.2f",s[5]);
            jsubt.setText(sb);
        }

    }//GEN-LAST:event_jCheckBox6MouseClicked

    private void jCheckBox7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox7MouseClicked
         double x=Double.parseDouble(jcost1.getText());
         double y=Double.parseDouble(jsubt.getText());
        double g1=Double.parseDouble(jTextField8.getText());
        double g2=40;
        if (jCheckBox7.isSelected())
        {
            i[6] =(g1*g2)+x;
            String z = String.format("%.2f",i[6]);
            jcost1.setText(z);
            s[6] =(g1*g2)+y;
            String sb = String.format("%.2f",s[6]);
            jsubt.setText(sb);
        }

    }//GEN-LAST:event_jCheckBox7MouseClicked

    private void jCheckBox8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox8MouseClicked
        double x=Double.parseDouble(jcost1.getText());
        double y=Double.parseDouble(jsubt.getText());
        double h1=Double.parseDouble(jTextField7.getText());
        double h2=30;
        if (jCheckBox8.isSelected())
        {
            i[7] =(h1*h2)+x;
            String z = String.format("%.2f",i[7]);
            jcost1.setText(z);
            s[7] =(h1*h2)+y;
            String sb = String.format("%.2f",s[7]);
            jsubt.setText(sb);
        }

    }//GEN-LAST:event_jCheckBox8MouseClicked

    private void jCheckBox9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox9MouseClicked
         double x=Double.parseDouble(jcost1.getText());
         double y=Double.parseDouble(jsubt.getText());
        double i1=Double.parseDouble(jTextField6.getText());
        double i2=90;
        if (jCheckBox9.isSelected())
        {
            i[8] =(i1*i2)+x;
            String z = String.format("%.2f",i[8]);
            jcost1.setText(z);
            s[8] =(i1*i2)+y;
            String sb = String.format("%.2f",s[8]);
            jsubt.setText(sb);
        }

    }//GEN-LAST:event_jCheckBox9MouseClicked

    private void jCheckBox10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox10MouseClicked
        double x=Double.parseDouble(jcost1.getText());
        double y=Double.parseDouble(jsubt.getText());
        double j1=Double.parseDouble(jTextField5.getText());
        double j2=40;
        if (jCheckBox10.isSelected())
        {
            i[9] =(j1*j2)+x;
            String z = String.format("%.2f",i[9]);
            jcost1.setText(z);
            s[9] =(j1*j2)+y;
            String sb = String.format("%.2f",s[9]);
            jsubt.setText(sb);
        }

    }//GEN-LAST:event_jCheckBox10MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        double X=Double.parseDouble(jcost2.getText());
        double yy=Double.parseDouble(jsubt.getText());
        double Y=Double.parseDouble(jtxtd.getText());
        double Tea=(15*Y)+X;
        t[0]=(15*Y)+yy;
        double Green_Tea=(25*Y)+X;
        t[1]=(25*Y)+yy;
        double Cappuccino=(100*Y)+X;
        t[2]=(100*Y)+yy;
        double Iced_Coffee=(65*Y)+X;
        t[3]=(65*Y)+yy;
        double Coffee_Milk=(70*Y)+X;
        t[4]=(70*Y)+yy;
        double Select=(0*Y)+X;
        t[5]=(0*Y)+yy;
        if (jComboBox1.getSelectedItem().equals("Select a item"))
        {
            String Z = String.format("%.2f",Select);
            jcost2.setText(Z);
            String sb0 = String.format("%.2f", t[5]);
            jsubt.setText(sb0);
        }
        if (jComboBox1.getSelectedItem().equals("Tea-15/-"))
        {
            String Z1 = String.format("%.2f",Tea);
            jcost2.setText(Z1);
            String sb1 = String.format("%.2f", t[0]);
            jsubt.setText(sb1);
        }
        if (jComboBox1.getSelectedItem().equals("Green Tea-25/-"))
        {
    
            String Z2 = String.format("%.2f",Green_Tea);
            jcost2.setText(Z2);
            String sb2 = String.format("%.2f", t[1]);
            jsubt.setText(sb2);
        }
        if (jComboBox1.getSelectedItem().equals("Cappuccino-100/-"))
        {
            
            String Z3 = String.format("%.2f",Cappuccino);
            jcost2.setText(Z3);
            String sb3 = String.format("%.2f", t[2]);
            jsubt.setText(sb3);
        }
         if (jComboBox1.getSelectedItem().equals("Iced Coffee-65/-"))
        {
            String Z4 = String.format("%.2f",Iced_Coffee);
            jcost2.setText(Z4);
            String sb4 = String.format("%.2f", t[3]);
            jsubt.setText(sb4);
        }   
         if (jComboBox1.getSelectedItem().equals("Coffee Milk-70/-"))
        {
            String Z5 = String.format("%.2f",Coffee_Milk);
            jcost2.setText(Z5);
            String sb5 = String.format("%.2f", t[4]);
            jsubt.setText(sb5);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        double X =Double.parseDouble(jcost2.getText());
        double yy =Double.parseDouble(jsubt.getText());
        double y=Double.parseDouble(jtxtd2.getText());
        double u7 =(15*y)+X;
        t[6] =(15*y)+yy;
        double coke=(15*y)+X;
        t[7]=(15*y)+yy;
        double mj=(40*y)+X;
        t[8]=(40*y)+yy;
        double aj=(35*y)+X;
        t[9]=(35*y)+yy;
        double oj=(35*y)+X;
        t[10]=(35*y)+yy;
        double Select2=(0*y)+X;
        t[11]=(0*y)+yy;
        
        if (jComboBox2.getSelectedItem().equals("Select a item"))
        {
            String Z = String.format("%.2f",Select2);
            jcost2.setText(Z);
            String sb0 = String.format("%.2f", t[11]);
            jsubt.setText(sb0);
        }
        if (jComboBox2.getSelectedItem().equals("7UP-15/-"))
        {
            String Z1 = String.format("%.2f",u7);
            jcost2.setText(Z1);
            String sb1 = String.format("%.2f", t[6]);
            jsubt.setText(sb1);
        }
        if (jComboBox2.getSelectedItem().equals("Coke-15/-"))
        {
    
            String Z2 = String.format("%.2f",coke);
            jcost2.setText(Z2);
            String sb2 = String.format("%.2f", t[7]);
            jsubt.setText(sb2);
        }
        if (jComboBox2.getSelectedItem().equals("Mango Juice-40/-"))
        {
            
            String Z3 = String.format("%.2f",mj);
            jcost2.setText(Z3);
            String sb3 = String.format("%.2f", t[8]);
            jsubt.setText(sb3);
        }
         if (jComboBox2.getSelectedItem().equals("Apple Juice-35/-"))
        {
            String Z4 = String.format("%.2f",aj);
            jcost2.setText(Z4);
            String sb4 = String.format("%.2f", t[9]);
            jsubt.setText(sb4);
        }   
         if (jComboBox2.getSelectedItem().equals("Orange Juice-35/-"))
        {
            String Z5 = String.format("%.2f",oj);
            jcost2.setText(Z5);
            String sb5 = String.format("%.2f", t[10]);
            jsubt.setText(sb5);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        double X =Double.parseDouble(jcost2.getText());
        double yy=Double.parseDouble(jsubt.getText());
        double y2=Double.parseDouble(jtxtd3.getText());
        double cm =(60*y2)+X;
        t[12] =(60*y2)+yy;
        double oic=(100*y2)+X;
        t[13]=(100*y2)+yy;
        double vvc=(80*y2)+X;
        t[14]=(80*y2)+yy;
        double cc=(90*y2)+X;
        t[15]=(90*y2)+yy;
        double fm=(80*y2)+X;
        t[16]=(80*y2)+yy;
        double Select3=(0*y2)+X;
        t[17]=(0*y2)+yy;
        
         if (jComboBox3.getSelectedItem().equals("Select a item"))
        {
            String Z5 = String.format("%.2f",Select3);
            jcost2.setText(Z5);
            String sb5 = String.format("%.2f", t[17]);
            jsubt.setText(sb5);
        }
        if (jComboBox3.getSelectedItem().equals("Coconut Milk-60/-"))
        {
            String Z = String.format("%.2f",cm);
            jcost2.setText(Z);
            String sb0 = String.format("%.2f", t[12]);
            jsubt.setText(sb0);
        }
        if (jComboBox3.getSelectedItem().equals("Original Iced Chocolate-100/-"))
        {
            String Z1 = String.format("%.2f",oic);
            jcost2.setText(Z1);
            String sb1 = String.format("%.2f", t[13]);
            jsubt.setText(sb1);
        }
        if (jComboBox3.getSelectedItem().equals("Very Vanilla Chiller-80/-"))
        {
    
            String Z2 = String.format("%.2f",vvc);
            jcost2.setText(Z2);
            String sb2 = String.format("%.2f", t[14]);
            jsubt.setText(sb2);
        }
        if (jComboBox3.getSelectedItem().equals("Cookies and Cream-90/-"))
        {
            
            String Z3 = String.format("%.2f",cc);
            jcost2.setText(Z3);
            String sb3 = String.format("%.2f", t[15]);
            jsubt.setText(sb3);
        }
         if (jComboBox3.getSelectedItem().equals("Fruize Mango-80/-"))
        {
            String Z4 = String.format("%.2f",fm);
            jcost2.setText(Z4);
            String sb4 = String.format("%.2f", t[16]);
            jsubt.setText(sb4);
        }   
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jCheckBox21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox21MouseClicked
         double dc=50;
         double dc0=0.00;
        if (jCheckBox21.isSelected())
        {
            String Cd = String.format("%.2f",dc);
            jdc.setText(Cd);
        }
        else
        {
            String Cd = String.format("%.2f",dc0);
            jdc.setText(Cd);
        }
    }//GEN-LAST:event_jCheckBox21MouseClicked

    private void jexit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexit1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jexit1ActionPerformed

    private void jcost2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcost2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcost2ActionPerformed

    private void jsubtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsubtMouseClicked
    }//GEN-LAST:event_jsubtMouseClicked

    private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox22ActionPerformed

    private void jCheckBox21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox21ActionPerformed

    private void jCheckBox22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox22MouseClicked
         double St =Double.parseDouble(jsubt.getText());
        double tax=St*(0.87/100);
        String ctax = String.format("%.2f",tax);
            jtax.setText(ctax);
    }//GEN-LAST:event_jCheckBox22MouseClicked

    private void jtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtotalActionPerformed
        double ST =Double.parseDouble(jsubt.getText());
        double Tax=Double.parseDouble(jtax.getText());
        double Dcg=Double.parseDouble(jdc.getText());
        double total=ST+Tax+Dcg;
        String Dtotal = String.format("%.2f",total);
            jdtotal.setText(Dtotal);
    }//GEN-LAST:event_jtotalActionPerformed

    private void jrsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrsetActionPerformed
        double temp=0.00;
        String stemp = String.format("%.2f",temp);
        jcost1.setText(stemp);
       jcost2.setText(stemp);
       jdc.setText(stemp);
       jdtotal.setText(stemp);
       jsubt.setText(stemp);
       jtax.setText(stemp);
       jTextField1.setText("TK. 30/- (BDT)");
       jTextField2.setText("TK. 40/- (BDT)");
       jTextField3.setText("TK. 30/- (BDT)");
       jTextField4.setText("TK. 30/- (BDT)");
       jTextField5.setText("TK. 40/- (BDT)");
       jTextField6.setText("TK. 90/- (BDT)");
       jTextField7.setText("TK. 30/- (BDT)");
       jTextField8.setText("TK. 40/- (BDT)");
       jTextField9.setText("TK. 30/- (BDT)");
       jTextField10.setText("TK. 20/- (BDT)");
       jTextField11.setText("TK. 30/- (BDT)");
       jTextField12.setText("TK. 40/- (BDT)");
       jTextField13.setText("TK. 40/- (BDT)");
       jTextField14.setText("TK. 50/- (BDT)");
       jTextField15.setText("TK. 60/- (BDT)");
       jTextField16.setText("TK. 100/- (BDT)");
       jTextField17.setText("TK. 120/- (BDT)");
       jTextField18.setText("TK. 200/- (BDT)");
       jTextField19.setText("TK. 215/- (BDT)");
       jTextField20.setText("TK. 300/- (BDT)");
       jtxtd.setText(null);
       jtxtd2.setText(null);
       jtxtd3.setText(null);
       jTextArea1.setText(null);
       jCheckBox1.setSelected(false);
       jCheckBox2.setSelected(false);
       jCheckBox3.setSelected(false);
       jCheckBox4.setSelected(false);
       jCheckBox5.setSelected(false);
       jCheckBox6.setSelected(false);
       jCheckBox7.setSelected(false);
       jCheckBox8.setSelected(false);
       jCheckBox9.setSelected(false);
       jCheckBox10.setSelected(false);
       jCheckBox11.setSelected(false);
       jCheckBox12.setSelected(false);
       jCheckBox13.setSelected(false);
       jCheckBox14.setSelected(false);
       jCheckBox15.setSelected(false);
       jCheckBox16.setSelected(false);
       jCheckBox17.setSelected(false);
       jCheckBox18.setSelected(false);
       jCheckBox19.setSelected(false);
       jCheckBox20.setSelected(false);
       
    }//GEN-LAST:event_jrsetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Boolean complete=jTextArea1.print();
            if (complete) {
                JOptionPane.showMessageDialog(null,"Done Printing...");
            }
            else
            { 
                JOptionPane.showMessageDialog(null,"Printing.....");
            }
        } catch (PrinterException ex) {
            Logger.getLogger(RestaurantFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void jrptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrptActionPerformed
        double R1 =Double.parseDouble(jcost1.getText());
        double R2=Double.parseDouble(jcost2.getText());
        double R3=Double.parseDouble(jtax.getText());
        double R4=Double.parseDouble(jdc.getText());
        double R5=Double.parseDouble(jdtotal.getText());
        jTextArea1.append("\tRestaurant Management System: \n\n" + "Cost Of Foods: \t\t"+R1+"\nCost of Drinks: \t\t"+R2+"\nTax: \t\t"+R3+"\nDelivery Charge:\t"+R4
        +"\nTotal Cost: \t\t"+R5+"\n\n\t*_*Thank you *_*");
    }//GEN-LAST:event_jrptActionPerformed

    private void jcalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcalculatorActionPerformed
        new RestaurantFrom_1().setVisible(true);
    }//GEN-LAST:event_jcalculatorActionPerformed

    private void jTextField11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField11MouseClicked
        jTextField11.setText(null); 
    }//GEN-LAST:event_jTextField11MouseClicked

    private void jTextField12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField12MouseClicked
        jTextField12.setText(null); 
    }//GEN-LAST:event_jTextField12MouseClicked

    private void jTextField13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField13MouseClicked
        jTextField13.setText(null); 
    }//GEN-LAST:event_jTextField13MouseClicked

    private void jTextField14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField14MouseClicked
       jTextField14.setText(null); 
    }//GEN-LAST:event_jTextField14MouseClicked

    private void jTextField15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField15MouseClicked
        jTextField15.setText(null); 
    }//GEN-LAST:event_jTextField15MouseClicked

    private void jTextField16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField16MouseClicked
        jTextField16.setText(null); 
    }//GEN-LAST:event_jTextField16MouseClicked

    private void jTextField17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField17MouseClicked
        jTextField17.setText(null); 
    }//GEN-LAST:event_jTextField17MouseClicked

    private void jTextField18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField18MouseClicked
        jTextField18.setText(null); 
    }//GEN-LAST:event_jTextField18MouseClicked

    private void jTextField19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField19MouseClicked
        jTextField19.setText(null); 
    }//GEN-LAST:event_jTextField19MouseClicked

    private void jTextField20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField20MouseClicked
        jTextField20.setText(null); 
    }//GEN-LAST:event_jTextField20MouseClicked

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox11MouseClicked
        double x=Double.parseDouble(jcost1.getText());
        double y=Double.parseDouble(jsubt.getText());
        double A1=Double.parseDouble(jTextField11.getText());
        double A2=30;
        if (jCheckBox11.isSelected())
        {
            i[10] =(A1*A2)+x;
            String z = String.format("%.2f",i[10]);
            jcost1.setText(z);
            s[10] =(A1*A2)+y;
            String sb = String.format("%.2f",s[10]);
            jsubt.setText(sb);
        }
    }//GEN-LAST:event_jCheckBox11MouseClicked

    private void jCheckBox12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox12MouseClicked
         double x=Double.parseDouble(jcost1.getText());
         double y=Double.parseDouble(jsubt.getText());
        double B1=Double.parseDouble(jTextField12.getText());
        double B2=40;
        if (jCheckBox12.isSelected())
        {
            i[11] =(B1*B2)+x;
            String z = String.format("%.2f",i[11]);
            jcost1.setText(z);
            s[11] =(B1*B2)+y;
            String sb = String.format("%.2f",s[11]);
            jsubt.setText(sb);
        }
    }//GEN-LAST:event_jCheckBox12MouseClicked

    private void jCheckBox13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox13MouseClicked
       double x=Double.parseDouble(jcost1.getText());
       double y=Double.parseDouble(jsubt.getText());
        double C1=Double.parseDouble(jTextField13.getText());
        double C2=40;
        if (jCheckBox13.isSelected())
        {
            i[12] =(C1*C2)+x;
            String z = String.format("%.2f",i[12]);
            jcost1.setText(z);
            s[12] =(C1*C2)+y;
            String sb = String.format("%.2f",s[12]);
            jsubt.setText(sb);
        }
    }//GEN-LAST:event_jCheckBox13MouseClicked

    private void jCheckBox14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox14MouseClicked
       double x=Double.parseDouble(jcost1.getText());
       double y=Double.parseDouble(jsubt.getText());
        double D1=Double.parseDouble(jTextField14.getText());
        double D2=50;
        if (jCheckBox14.isSelected())
        {
            i[13] =(D1*D2)+x;
            String z = String.format("%.2f",i[13]);
            jcost1.setText(z);
            s[13] =(D1*D2)+y;
            String sb = String.format("%.2f",s[13]);
            jsubt.setText(sb);
        }
    }//GEN-LAST:event_jCheckBox14MouseClicked

    private void jCheckBox15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox15MouseClicked
        double x=Double.parseDouble(jcost1.getText());
        double y=Double.parseDouble(jsubt.getText());
        double E1=Double.parseDouble(jTextField15.getText());
        double E2=60;
        if (jCheckBox15.isSelected())
        {
            i[14] =(E1*E2)+x;
            String z = String.format("%.2f",i[14]);
            jcost1.setText(z);
            s[14] =(E1*E2)+y;
            String sb = String.format("%.2f",s[14]);
            jsubt.setText(sb);
        }
    }//GEN-LAST:event_jCheckBox15MouseClicked

    private void jCheckBox16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox16MouseClicked
        double x=Double.parseDouble(jcost1.getText());
        double y=Double.parseDouble(jsubt.getText());
        double F1=Double.parseDouble(jTextField16.getText());
        double F2=100;
        if (jCheckBox16.isSelected())
        {
            i[15] =(F1*F2)+x;
            String z = String.format("%.2f",i[15]);
            jcost1.setText(z);
            s[15] =(F1*F2)+y;
            String sb = String.format("%.2f",s[15]);
            jsubt.setText(sb);
        }
    }//GEN-LAST:event_jCheckBox16MouseClicked

    private void jCheckBox17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox17MouseClicked
        double x=Double.parseDouble(jcost1.getText());
        double y=Double.parseDouble(jsubt.getText());
        double G1=Double.parseDouble(jTextField17.getText());
        double G2=120;
        if (jCheckBox17.isSelected())
        {
            i[16] =(G1*G2)+x;
            String z = String.format("%.2f",i[16]);
            jcost1.setText(z);
            s[16] =(G1*G2)+y;
            String sb = String.format("%.2f",s[16]);
            jsubt.setText(sb);
        }
    }//GEN-LAST:event_jCheckBox17MouseClicked

    private void jCheckBox18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox18MouseClicked
        double x=Double.parseDouble(jcost1.getText());
        double y=Double.parseDouble(jsubt.getText());
        double H1=Double.parseDouble(jTextField18.getText());
        double H2=200;
        if (jCheckBox18.isSelected())
        {
            i[17] =(H1*H2)+x;
            String z = String.format("%.2f",i[17]);
            jcost1.setText(z);
            s[17] =(H1*H2)+y;
            String sb = String.format("%.2f",s[17]);
            jsubt.setText(sb);
        }
    }//GEN-LAST:event_jCheckBox18MouseClicked

    private void jCheckBox19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox19MouseClicked
        double x=Double.parseDouble(jcost1.getText());
        double y=Double.parseDouble(jsubt.getText());
        double I1=Double.parseDouble(jTextField19.getText());
        double I2=215;
        if (jCheckBox19.isSelected())
        {
            i[18] =(I1*I2)+x;
            String z = String.format("%.2f",i[18]);
            jcost1.setText(z);
            s[18] =(I1*I2)+y;
            String sb = String.format("%.2f",s[18]);
            jsubt.setText(sb);
        }
    }//GEN-LAST:event_jCheckBox19MouseClicked

    private void jCheckBox20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox20MouseClicked
       double x=Double.parseDouble(jcost1.getText());
       double y=Double.parseDouble(jsubt.getText());
        double J1=Double.parseDouble(jTextField20.getText());
        double J2=300;
        if (jCheckBox20.isSelected())
        {
            i[19] =(J1*J2)+x;
            String z = String.format("%.2f",i[19]);
            jcost1.setText(z);
            s[19] =(J1*J2)+y;
            String sb = String.format("%.2f",s[19]);
            jsubt.setText(sb);
        }
    }//GEN-LAST:event_jCheckBox20MouseClicked

    private void jcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcashActionPerformed
        new RestaurantFrom_2().setVisible(true);
    }//GEN-LAST:event_jcashActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton jcalculator;
    private javax.swing.JButton jcash;
    private javax.swing.JTextField jcost1;
    private javax.swing.JTextField jcost2;
    private javax.swing.JTextField jdc;
    private javax.swing.JTextField jdtotal;
    private javax.swing.JButton jexit1;
    private javax.swing.JButton jrpt;
    private javax.swing.JButton jrset;
    private javax.swing.JTextField jsubt;
    private javax.swing.JTextField jtax;
    private javax.swing.JButton jtotal;
    private javax.swing.JTextField jtxtd;
    private javax.swing.JTextField jtxtd2;
    private javax.swing.JTextField jtxtd3;
    // End of variables declaration//GEN-END:variables
}
